# coding: utf-8

"""
    Trend Micro Workload Security API

    Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # noqa: E501

    OpenAPI spec version: 50.0.810
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CommonObjectInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'common_object_id': 'int',
        'common_object_name': 'str'
    }

    attribute_map = {
        'common_object_id': 'commonObjectID',
        'common_object_name': 'commonObjectName'
    }

    def __init__(self, common_object_id=None, common_object_name=None):  # noqa: E501
        """CommonObjectInfo - a model defined in Swagger"""  # noqa: E501

        self._common_object_id = None
        self._common_object_name = None
        self.discriminator = None

        if common_object_id is not None:
            self.common_object_id = common_object_id
        if common_object_name is not None:
            self.common_object_name = common_object_name

    @property
    def common_object_id(self):
        """Gets the common_object_id of this CommonObjectInfo.  # noqa: E501

        Common object id  # noqa: E501

        :return: The common_object_id of this CommonObjectInfo.  # noqa: E501
        :rtype: int
        """
        return self._common_object_id

    @common_object_id.setter
    def common_object_id(self, common_object_id):
        """Sets the common_object_id of this CommonObjectInfo.

        Common object id  # noqa: E501

        :param common_object_id: The common_object_id of this CommonObjectInfo.  # noqa: E501
        :type: int
        """

        self._common_object_id = common_object_id

    @property
    def common_object_name(self):
        """Gets the common_object_name of this CommonObjectInfo.  # noqa: E501

        Common object name  # noqa: E501

        :return: The common_object_name of this CommonObjectInfo.  # noqa: E501
        :rtype: str
        """
        return self._common_object_name

    @common_object_name.setter
    def common_object_name(self, common_object_name):
        """Sets the common_object_name of this CommonObjectInfo.

        Common object name  # noqa: E501

        :param common_object_name: The common_object_name of this CommonObjectInfo.  # noqa: E501
        :type: str
        """

        self._common_object_name = common_object_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CommonObjectInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CommonObjectInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

