# coding: utf-8

"""
    Trend Micro Workload Security API

    Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # noqa: E501

    OpenAPI spec version: 50.0.810
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from deepsecurity.models.policy_info import PolicyInfo  # noqa: F401,E501


class PolicyMapping(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'import_to': 'PolicyInfo',
        'import_from': 'PolicyInfo'
    }

    attribute_map = {
        'import_to': 'importTo',
        'import_from': 'importFrom'
    }

    def __init__(self, import_to=None, import_from=None):  # noqa: E501
        """PolicyMapping - a model defined in Swagger"""  # noqa: E501

        self._import_to = None
        self._import_from = None
        self.discriminator = None

        if import_to is not None:
            self.import_to = import_to
        if import_from is not None:
            self.import_from = import_from

    @property
    def import_to(self):
        """Gets the import_to of this PolicyMapping.  # noqa: E501

        New policy on Workload Security  # noqa: E501

        :return: The import_to of this PolicyMapping.  # noqa: E501
        :rtype: PolicyInfo
        """
        return self._import_to

    @import_to.setter
    def import_to(self, import_to):
        """Sets the import_to of this PolicyMapping.

        New policy on Workload Security  # noqa: E501

        :param import_to: The import_to of this PolicyMapping.  # noqa: E501
        :type: PolicyInfo
        """

        self._import_to = import_to

    @property
    def import_from(self):
        """Gets the import_from of this PolicyMapping.  # noqa: E501

        Policy on Deep Security Manager  # noqa: E501

        :return: The import_from of this PolicyMapping.  # noqa: E501
        :rtype: PolicyInfo
        """
        return self._import_from

    @import_from.setter
    def import_from(self, import_from):
        """Sets the import_from of this PolicyMapping.

        Policy on Deep Security Manager  # noqa: E501

        :param import_from: The import_from of this PolicyMapping.  # noqa: E501
        :type: PolicyInfo
        """

        self._import_from = import_from

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PolicyMapping, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PolicyMapping):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

